name: Website Ping Check

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜 0 點執行一次
  workflow_dispatch: # 可手動觸發

jobs:
  ping-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ping website
        id: ping
        run: |
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" https://example.com)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Website is down."
            echo "status=down" >> $GITHUB_ENV
          else
            echo "Website is up."
            echo "status=up" >> $GITHUB_ENV

      - name: Send email if down
        if: env.status == 'down'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Website Down Alert"
          body: "The website https://example.com is not responding."
          to: recipient@example.com
          from: ${{ secrets.GMAIL_USERNAME }}
