name: Website Ping Check

on:
  schedule:
    - cron: '0 4 * * *' # 每天 00:00 UTC
  workflow_dispatch: # 可手動觸發

jobs:
  ping-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ping website
        id: ping
        run: |
          RESPONSE=$(curl -s https://turtle-hot-completely.ngrok-free.app/alive)
          
          if echo "$RESPONSE" | grep -q '<div[^>]*id="alive"'; then
            echo "The <div id='alive'> exists."
            echo "status=up" >> $GITHUB_ENV
          else
            echo "The <div id='alive'> does not exist."
            echo "status=down" >> $GITHUB_ENV
          fi

      - name: Send LINE message if down
        if: env.status == 'down'
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Authorization: Bearer ${{ secrets.LineMsgToken }}" \
          -H "Content-Type: application/json" \
          -d '{
            "to": " ${{ secrets.LineMsgMeID }}",
            "messages": [
              {
                "type": "text",
                "text": "浩子的主機沒有回應"
              }
            ]
          }'
